# Generated by Django 4.2.4 on 2023-09-15 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f8722ac-cb9c-4562-9706-848111e268f6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
